sudo: false
language: ruby
rvm:
  - 2.3.5
  - 2.4.1
before_install: gem install bundler -v 1.14.6
script:
  - bundle exec rspec
  - bundle exec ruby -I test -e 'Dir["./test/**/*_test.rb"].each &method(:require)'
